database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "nanu123"
  dbname: "mutualfunds"

source:
  csv_path: "data/mutual_fund.csv"
  mf_list_url: "https://api.mfapi.in/mf"
  mf_detail_url_template: "https://api.mfapi.in/mf/{schemeCode}"
  mf_latest_url_template: "https://api.mfapi.in/mf/{schemeCode}/latest"

fetch:
  top_n: 10
  sleep_seconds: 0.5
